# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _NIRScanner
else:
    import _NIRScanner

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class NIRScanner(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, pConfig=None):
        _NIRScanner.NIRScanner_swiginit(self, _NIRScanner.new_NIRScanner(pConfig))
    __swig_destroy__ = _NIRScanner.delete_NIRScanner

    def readVersion(self):
        return _NIRScanner.NIRScanner_readVersion(self)

    def resetErrorStatus(self):
        return _NIRScanner.NIRScanner_resetErrorStatus(self)

    def setLampOnOff(self, newValue):
        return _NIRScanner.NIRScanner_setLampOnOff(self, newValue)

    def setConfig(self, scanConfigIndex, scan_type, num_patterns, num_repeats, wavelength_start_nm, wavelength_end_nm, width_px, exposure_time, ScanConfig_serial_number, config_name):
        return _NIRScanner.NIRScanner_setConfig(self, scanConfigIndex, scan_type, num_patterns, num_repeats, wavelength_start_nm, wavelength_end_nm, width_px, exposure_time, ScanConfig_serial_number, config_name)

    def configEVM(self, pConfig=None):
        return _NIRScanner.NIRScanner_configEVM(self, pConfig)

    def setPGAGain(self, newValue):
        return _NIRScanner.NIRScanner_setPGAGain(self, newValue)

    def scanSNR(self, isHadamard=True):
        return _NIRScanner.NIRScanner_scanSNR(self, isHadamard)

    def scan(self, saveDataFlag=False, numRepeats=1):
        return _NIRScanner.NIRScanner_scan(self, saveDataFlag, numRepeats)

    def getScanData(self):
        return _NIRScanner.NIRScanner_getScanData(self)

    def setHibernate(self, newValue):
        return _NIRScanner.NIRScanner_setHibernate(self, newValue)

# Register NIRScanner in _NIRScanner:
_NIRScanner.NIRScanner_swigregister(NIRScanner)



